### PR TITLE
First commit to pr

### PR DESCRIPTION
**Pull request by ZenginU**
not sure if I did this commit thinggy right

### CODE REVIEW

**Comment by ZenginU** [comment]
leave it as draft so you can pick with implementation you like most

**Comment by geohotstan** [comment]
Ooooooo I have no idea how this thingy works either LOL
we can keep the original with the nice spacing
Never thought I'd have the luxury of clicking merge on a pr, feels kinda weird.
Thanks a bunch :D :D :D :D :D

**Comment by ZenginU** [comment]
No worries I still dont know if this is the correct way lmao, are we allowed to use np.complex for complex required onnx ops?

**Comment by geohotstan** [comment]
> No worries I still dont know if this is the correct way lmao, are we allowed to use np.complex for complex required onnx ops?

yeah I think so?
Before Tensor.pad() had constant padding, there was code with np.pad() that handled the constant padding in the onnx code so I think it's fine.

**Comment by ZenginU** [comment]
oh okay, btw I can also write you from discord instead of PR comments.
Also, I like to mention that I dont have an eye on the bounty. I like to do this windows and other numeric stuff for the sake of electrical eng degree it may be usefull for the first time lmao

**Comment by ZenginU** [comment]
What is your discord 😄

**Pull request merged**
